### ISSUE TITLE
Unrecognized Currency Timeouts

### ISSUE THREAD

**Issue by tridaak** [ericgrandt/TotalEconomy#285]
Sponge Version:  SpongeForge-1.12.2-2705-7.1.0-BETA-3148
Forge Version:  Forge 14.23.4.2705
Total Economy Version:  TotalEconomy-1.8.1

### Description of issue
Whenever a player runs baltop (guessing bal as well, but haven't tried it) for a currency that doesn't exist, the server will kick everyone out and not let anyone in (timeouts). It seems to keep trying to run the command even minutes after it errors.

### Console errors
```
[17:25:44] [Server thread/INFO] [nucleus]: Hotshot6404 ran the command: /baltop pokebonds
[17:26:14] [Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[17:26:14] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Tridaak lost connection: Disconnected
[17:26:14] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [-] Tridaak
[17:26:14] [Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.channel.unix.Errors$NativeIoException: syscall:write(..) failed: Broken pipe
        at io.netty.channel.unix.FileDescriptor.writeAddress(..)(Unknown Source) ~[FileDescriptor.class:?]
[17:26:15] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: SnapCrackle3 lost connection: Timed out
[17:26:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [-] SnapCrackle3
[17:26:15] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 30821ms behind, skipping 616 tick(s)
[17:26:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Veteran] Tridaak: There is not baltop 2 though I:
[17:26:15] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Hotshot6404 lost connection: Disconnected
[17:26:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [-] Hotshot6404
[17:26:19] [User Authenticator #6/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player Hotshot6404 is e0d95a8e-262b-4390-bf4f-b1b1c47b9025
[17:26:19] [Netty Epoll Server IO #3/INFO] [FML]: Client protocol version 2
[17:26:19] [Netty Epoll Server IO #3/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.4.2705,mcp@9.42,pixelmon@6.3.1
[17:26:19] [Netty Epoll Server IO #3/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, command-utils, griefprevention, luckperms, nucleus, pixelextras, pixelmoneconomybridge, pixelupgrade, placeholderapi, playerglo
w, totaleconomy, virtualchest, webapi, webapi-api, worldedit, yourcustompaintings, zpixelmonplaceholders] at CLIENT
[17:26:20] [User Authenticator #7/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player SnapCrackle3 is ea86bdac-6b74-412a-9560-65aafa43bd5e
[17:26:20] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[17:26:20] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Hotshot6404[/75.174.201.222:57066] logged in with entity id 1102 in rtg(3) at (1284.0356485854438, 72.72359997034073, 1223.7449407274598)
[17:26:20] [Server thread/WARN] [net.minecraft.entity.EntityList]: Skipping Entity with id minecraft:
[17:26:20] [Netty Epoll Server IO #0/INFO] [FML]: Client protocol version 2
[17:26:20] [Netty Epoll Server IO #0/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.4.2707,mcp@9.42,pixelmon@6.3.1
[17:26:20] [Netty Epoll Server IO #0/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, command-utils, griefprevention, luckperms, nucleus, pixelextras, pixelmoneconomybridge, pixelupgrade, placeholderapi, playerglo
w, totaleconomy, virtualchest, webapi, webapi-api, worldedit, yourcustompaintings, zpixelmonplaceholders] at CLIENT
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.executeQuery(SqlQuery.java:58)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.<init>(SqlQuery.java:48)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.<init>(SqlQuery.java:35)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery$Builder.build(SqlQuery.java:335)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.config.AccountManager.hasAccount(AccountManager.java:276)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:215)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.main.TotalEconomy.onPlayerJoin(TotalEconomy.java:233)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.listener.JoinListener_TotalEconomy_onPlayerJoin38.handle(Unknown Source)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1672)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at java.lang.Thread.run(Thread.java:748)
[17:26:50] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.8.1, description=All in one economy plugin for Minecraft/Sponge, source=./mods/TotalEconomy-1.8.1.jar}
java.lang.NullPointerException: null
        at com.erigitic.sql.SqlQuery.recordExists(SqlQuery.java:100) ~[SqlQuery.class:?]
        at com.erigitic.config.AccountManager.hasAccount(AccountManager.java:278) ~[AccountManager.class:?]
        at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:215) ~[AccountManager.class:?]
        at com.erigitic.main.TotalEconomy.onPlayerJoin(TotalEconomy.java:233) ~[TotalEconomy.class:?]
        at org.spongepowered.common.event.listener.JoinListener_TotalEconomy_onPlayerJoin38.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3148]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1672) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[17:26:51] [Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.executeQuery(SqlQuery.java:58)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.<init>(SqlQuery.java:48)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery.<init>(SqlQuery.java:35)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.sql.SqlQuery$Builder.build(SqlQuery.java:335)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.config.AccountManager.hasAccount(AccountManager.java:276)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:215)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.reforged.pixelmoneconomybridge.PixelmonEconomyBridge.getBankAccount(PixelmonEconomyBridge.java:95)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at com.reforged.pixelmoneconomybridge.PixelmonEconomyBridge.onPlayerJoin(PixelmonEconomyBridge.java:89)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.listener.JoinListener_PixelmonEconomyBridge_onPlayerJoin26.handle(Unknown Source)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1672)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[17:27:20] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]:  at java.lang.Thread.run(Thread.java:748)
[17:27:20] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=pixelmoneconomybridge, name=PixelmonEconomyBridge, version=2.0.1, description=A plugin to overlay Pixelmon currency with SpongeAPI economy, source=./mods/PixelmonEconomyBridge-1.12.2-2.0.1.jar}
java.lang.NullPointerException: null
        at com.erigitic.sql.SqlQuery.recordExists(SqlQuery.java:100) ~[SqlQuery.class:?]
        at com.erigitic.config.AccountManager.hasAccount(AccountManager.java:278) ~[AccountManager.class:?]
        at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:215) ~[AccountManager.class:?]
        at com.reforged.pixelmoneconomybridge.PixelmonEconomyBridge.getBankAccount(PixelmonEconomyBridge.java:95) ~[PixelmonEconomyBridge.class:?]
        at com.reforged.pixelmoneconomybridge.PixelmonEconomyBridge.onPlayerJoin(PixelmonEconomyBridge.java:89) ~[PixelmonEconomyBridge.class:?]
        at org.spongepowered.common.event.listener.JoinListener_PixelmonEconomyBridge_onPlayerJoin26.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3148]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3148]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1672) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

### Steps to reproduce
Not sure which is the cause, but this is how it's set up on my server:
Database is enabled and stores all currency information in a mysql table. Works fine regularly, creates the tables, can pay, change balance, etc.
I have two currencies, one called dollar and the other called bond (though call it a pokebond when talking about it outside of commands).
Running baltop [currency] for a currency that exists runs properly, running baltop <currency> for a currency that does not exist also runs (though returns the default currency)... Running baltop  <currency> for a currency that does not exist kicks everyone from the server and does not let anyone rejoin.

### Other
Could it also be possible to create currency aliases so that users don't accidentally type the wrong currency name?

**Comment by MarkL4YG** [comment]
Please attach your full server log as a gist. This reads itself like there's more than one thing not going according to plan.

**Comment by tridaak** [comment]
https://gist.github.com/tridaak/df9e224fd99c94bf32cc0403ca1a3799

Here it is.

**Comment by MarkL4YG** [comment]
> [17:26:50] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:executeQuery:68]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.  
  
How well is the status of your database server and how good is the connection to it?  
Are you connecting to ``localhost`` or are you connecting to a remote site?

**Comment by tridaak** [comment]
It's localhost, have (or have had) several plugins use the mysql database, never had an issue with it being too slow, usually runs pretty smoothly, can change database and player's balances update right away so don't think it's connecting to the database slowly. 
But baltop seems to have problems, sometimes I can run it fine, but seems sooner or later it'll have problems connecting. Thought it was just from running baltop as a player with a currency that doesn't exist, but run into the same problem when running the command from console (just /baltop) and tried it in game after, and was able to run /baltop with a non existent currency name (though kept trying and eventually timeout problems)

**Comment by MarkL4YG** [comment]
That's interresting. I may do a few benchmarks in order to get an idea about what may be going on.
I suspect that the current table schema may be playing a role here.
