### ISSUE TITLE
Can't launch Total Economy on Sponge server

### ISSUE THREAD

**Issue by CheeseWaffle69** [ericgrandt/TotalEconomy#420]
Minecraft version: 1.19.4
Sponge version: spongeforge-1.19.4-45.1.19-10.0.0-RC1588-universal
Plugin version: TotalEconomy-0.12.1

2024-07-08 00:30:51,904 main WARN Advanced terminal features are not available in this environment
[00:30:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 45.3.0, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934]
[00:30:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 21.0.2 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[00:30:52] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Korben/Desktop/Server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[00:30:52] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\fmlcore\1.19.4-45.3.0\fmlcore-1.19.4-45.3.0.jar is missing mods.toml file
[00:30:52] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\javafmllanguage\1.19.4-45.3.0\javafmllanguage-1.19.4-45.3.0.jar is missing mods.toml file
[00:30:52] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\lowcodelanguage\1.19.4-45.3.0\lowcodelanguage-1.19.4-45.3.0.jar is missing mods.toml file
[00:30:52] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\mclanguage\1.19.4-45.3.0\mclanguage-1.19.4-45.3.0.jar is missing mods.toml file
[00:30:52] [main/INFO] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Scanning and verifying libraries in '.\sponge-libraries'. Please wait, this may take a moment...
[00:30:52] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.module.ResolutionException: Module net.kyori.adventure.key contains package net.kyori.adventure.key, module totaleconomy exports package net.kyori.adventure.key to net.kyori.adventure.key
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:806)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Press any key to continue . . .

**Comment by ericgrandt** [comment]
Hi @CheeseWaffle69, do you have any other plugins installed or just Total Economy?

**Comment by CheeseWaffle69** [comment]
I tried running it without any plugins or mods and it still didn't work

**Comment by ericgrandt** [comment]
Alright, I think I know what the issue is. Would you be willing to try this version attached below? It's an updated 0.12.1 Total Economy jar file within a zip, hopefully with a working fix. 

[TotalEconomy-0.12.1.zip](https://github.com/user-attachments/files/16135685/TotalEconomy-0.12.1.zip)

**Comment by CheeseWaffle69** [comment]
I tried what you sent me without any other plugins or mods installed besides spongeapi and your total economy plugin. Here is what the console exported:

[20:50:31] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\javafmllanguage\1.19.4-45.3.0\javafmllanguage-1.19.4-45.3.0.jar is missing mods.toml file
[20:50:31] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\lowcodelanguage\1.19.4-45.3.0\lowcodelanguage-1.19.4-45.3.0.jar is missing mods.toml file
[20:50:31] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Korben\Desktop\Server\libraries\net\minecraftforge\mclanguage\1.19.4-45.3.0\mclanguage-1.19.4-45.3.0.jar is missing mods.toml file
[20:50:31] [main/INFO] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Scanning and verifying libraries in '.\sponge-libraries'. Please wait, this may take a moment...
[20:50:31] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.module.ResolutionException: Module com.zaxxer.hikari contains package com.zaxxer.hikari.metrics.dropwizard, module totaleconomy exports package com.zaxxer.hikari.metrics.dropwizard to com.zaxxer.hikari
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:806)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Press any key to continue . . .

**Comment by ericgrandt** [comment]
Sweet, progress; no longer erroring out for net.kyori.adventure. So on the right track I think.

**Comment by CheeseWaffle69** [comment]
Sweet man, thank you. Take your time I'll be available whenever you're ready :)

**Comment by ericgrandt** [comment]
Also, if you're only playing on Vanilla Minecraft, you can use SpongeVanilla instead of SpongeForge which shouldn't have this issue. I know the reason for the issue, though a fix is going to take some time as it's a potentially large fix.

**Comment by CheeseWaffle69** [comment]
okay that is fine it is a modded server so take your time and ill download the version when its fixed thank you for your help

**Comment by ericgrandt** [comment]
Hi @CheeseWaffle69 apologies for the delay, could you try the build attached to this comment (it's a jar within a zip file again). I was able to recreate then fix the issue on my end with SpongeForge 1.21.1.

[TotalEconomy-0.13.1.zip](https://github.com/user-attachments/files/16738080/TotalEconomy-0.13.1.zip)

**Comment by ericgrandt** [comment]
Available for download from Modrinth: https://modrinth.com/plugin/total-economy/version/0.13.1
